baseURL = 'https://hacdias.com/'
languageCode = 'en'
title = 'Henrique Dias'
pluralizeListTitles = false
removePathAccents = true
capitalizeListTitles = true
summaryLength = 100
printPathWarnings = true

[pagination]
  pagerSize = 15

[taxonomies]
  tag = 'tags'
  category = 'categories'

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:contentbasename/'
    categories = '/:sections[1:]/:contentbasename/'
  [permalinks.term]
    tags = '/tags/:contentbasename/'
    categories = '/:contentbasename/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false

[menu]
[[menu.main]]
  name = '🧁 About'
  pageRef = '/about'
  weight = 1
[[menu.main]]
  name = '✏️ Writings'
  pageRef = '/categories/writings'
  weight = 2
[[menu.main]]
  name = '📷 Photos'
  pageRef = '/categories/photos'
  weight = 3
[[menu.main]]
  name = '📖 Guestbook'
  pageRef = '/guestbook'
  weight = 4
[[menu.main]]
  name = '🔎 Search'
  pageRef = '/search'
  weight = 5
[[menu.main]]
  name = '🌈 More'
  pageRef = '/more'
  weight = 6

[[menu.contact]]
  name = '✉️ Email'
  url = 'mailto:mail@hacdias.com'
  weight = 1
[[menu.contact]]
  name = '💬 Signal'
  url = 'https://signal.me/#eu/NpDa7rvcj4CAXsiOpHqM2ADYyxXXmGTKr3HBXNPZXDPJ2JEgvBVPyJJah27RJe66'
  weight = 2

[[menu.elsewhere]]
  name = '🦋 Bluesky'
  url = 'https://bsky.app/profile/hacdias.com'
  weight = 1
[[menu.elsewhere]]
  name = '🐙 GitHub'
  url = 'https://github.com/hacdias'
  weight = 2
[[menu.elsewhere]]
  name = '📷 Instagram'
  url = 'https://instagram.com/hacdias'
  weight = 3
[[menu.elsewhere]]
  name = '🐘 Mastodon'
  url = 'https://fosstodon.org/@hacdias'
  weight = 4
[[menu.elsewhere]]
  name = '💼 LinkedIn'
  url = 'https://linkedin.com/in/hacdias'
  weight = 5

[params]
  [params.site]
    description = "Henrique is a software engineer who is passionate about open source, digital identity, web technology, and user agency. In his free time, he enjoys staying active, programming, photography, and a tasty cup of coffee or tea."
  [params.author]
    name = 'Henrique Dias'
    email = 'mail@hacdias.com'
    photo = 'https://hacdias.com/avatar/512.jpg'
    fediverse = '@hacdias@fosstodon.org'
    handle = 'hacdias'
    identities = [
      'https://github.com/hacdias',
      'https://instagram.com/hacdias',
      'https://fosstodon.org/@hacdias',
      'https://linkedin.com/in/hacdias',
      'https://discord.com/users/hacdias',
      'https://bsky.app/profile/hacdias.com',
      'https://reddit.com/u/hacdias',
      'mailto:mail@hacdias.com'
    ]

[mediaTypes.'application/atom+xml']
  suffixes = ['xml']
[mediaTypes.'text/xsl']
  suffixes = ['xsl']

[outputFormats]
  [outputFormats.atom]
    baseName = 'feed'
    mediaType = 'application/atom+xml'
    isPlainText = false
    rel = 'alternate'
    noUgly = true
    permalinkable = false
  [outputFormats.json]
    baseName = 'feed'
    mediaType = 'application/json'
    isPlainText = true
    rel = 'alternate'
    noUgly = true
    permalinkable = false
  [outputFormats.feedXsl]
    baseName = 'feed'
    mediaType = 'text/xsl'
    isPlainText = true
    notAlternative = true
    noUgly = true
  [outputFormats.sitemapXsl]
    baseName = 'sitemap'
    mediaType = 'text/xsl'
    isPlainText = true
    notAlternative = true
    noUgly = true

[outputs]
  taxonomy = ['HTML']
  term = ['HTML', 'ATOM', 'JSON']
  home = ['HTML', 'ATOM', 'JSON', 'FEEDXSL', 'SITEMAPXSL']
  section = ['HTML']
  page = ['HTML']

[services]
  [services.rss]
    limit = 10
